FROM adoptopenjdk/openjdk11:alpine-jre
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} workspace/app.jar
ENTRYPOINT ["java","-jar","/workspace/app.jar"]
RUN mkdir -p /workspace/storage && chmod 777 /workspace/storage